#!/bin/bash -eu

PID_FILE="/tmp/$1.toggle"

if [ -f "$PID_FILE" ]; then
	if $(kill $(cat $PID_FILE)); then
		rm $PID_FILE
		exit 0
	fi
fi

#Launch our executable
$1 &

# Save spawned process pid
echo $! > $PID_FILE
